# Generated by Django 4.1.2 on 2022-11-11 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Journal', '0006_alter_todolist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
        migrations.AddField(
            model_name='todolist',
            name='user',
            field=models.ManyToManyField(null=True, related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
