# Generated by Django 4.1.2 on 2022-11-12 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Journal', '0007_remove_todolist_user_todolist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
        migrations.AddField(
            model_name='todolist',
            name='user_lists',
            field=models.ManyToManyField(null=True, related_name='user_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
