# Generated by Django 4.1.2 on 2022-11-12 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Journal', '0008_remove_todolist_user_todolist_user_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='user_lists',
            field=models.ManyToManyField(related_name='user_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
