# Generated by Django 4.1.2 on 2022-11-29 15:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GI', 'Gi'), ('NOGI', 'No Gi'), ('GYM', 'Gym')], max_length=16)),
                ('date', models.DateField(default=datetime.date.today)),
                ('location', models.CharField(max_length=50)),
                ('length', models.SmallIntegerField()),
                ('notes', models.CharField(max_length=300)),
                ('techniques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkoutJournal.technique')),
            ],
        ),
    ]
