# Generated by Django 4.1.2 on 2022-12-22 08:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Choke', 'Choke'), ('Throw', 'Throw'), ('Lever', 'Lever'), ('Sweep', 'Sweep'), ('Position', 'Position')], max_length=15)),
                ('EnglishName', models.CharField(max_length=42, unique=True)),
                ('otherName', models.CharField(blank=True, max_length=32)),
                ('description', models.CharField(blank=True, max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GI', 'GI'), ('NOGI', 'NOGI'), ('GYM', 'GYM')], max_length=16)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('notes', models.TextField(blank=True, max_length=2500, null=True)),
                ('addedByUser', models.ManyToManyField(blank=True, related_name='addedByUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2500)),
                ('addedByUser', models.ManyToManyField(default=None, related_name='suggestedByUser', to=settings.AUTH_USER_MODEL)),
                ('technique', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkoutJournal.technique')),
            ],
        ),
    ]
