# Generated by Django 4.1.2 on 2022-12-18 12:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Choke', 'Choke'), ('Throw', 'Throw'), ('Lever', 'Lever'), ('Sweep', 'Sweep'), ('Position', 'Position')], max_length=15)),
                ('EnglishName', models.CharField(max_length=42, unique=True)),
                ('otherName', models.CharField(blank=True, max_length=32)),
                ('description', models.CharField(blank=True, max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GI', 'Gi'), ('NOGI', 'No Gi'), ('GYM', 'Gym')], max_length=16)),
                ('date', models.DateField(default=datetime.date.today)),
                ('location', models.CharField(max_length=50)),
                ('length', models.IntegerField()),
                ('notes', models.CharField(max_length=300)),
                ('addedByUser', models.ManyToManyField(related_name='user_session', to=settings.AUTH_USER_MODEL)),
                ('techniques', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkoutJournal.technique')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2500)),
                ('addedByUser', models.ManyToManyField(default=None, related_name='suggestedByUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
