# Generated by Django 4.1.2 on 2022-12-01 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WorkoutJournal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='user_session',
            field=models.ManyToManyField(related_name='user_session', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='techniques',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkoutJournal.technique'),
        ),
    ]
