# Generated by Django 4.1.2 on 2022-12-18 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutJournal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='technique',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkoutJournal.technique'),
        ),
    ]
