# Generated by Django 4.1.2 on 2022-12-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutJournal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='techniques',
            field=models.ManyToManyField(blank=True, to='WorkoutJournal.technique'),
        ),
    ]
