# Generated by Django 4.1.2 on 2023-02-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutJournal', '0002_trainingsession_techniques'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsession',
            old_name='length',
            new_name='hoursLength',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='fightTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='minutesLength',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True),
        ),
    ]
