# Generated by Django 4.1.2 on 2022-12-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutJournal', '0002_trainingsession_user_session_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsession',
            old_name='user_session',
            new_name='addedByUser',
        ),
    ]
