# Generated by Django 4.1.2 on 2022-12-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutJournal', '0002_suggestion_technique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='type',
            field=models.CharField(choices=[('GI', 'GI'), ('NOGI', 'NOGI'), ('GYM', 'GYM')], max_length=16),
        ),
    ]
