# Generated by Django 4.1.2 on 2023-02-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutJournal', '0003_rename_length_trainingsession_hourslength_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='minutesLength',
            field=models.IntegerField(null=True),
        ),
    ]
