# Generated by Django 4.1.2 on 2022-12-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutJournal', '0003_rename_user_session_trainingsession_addedbyuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technique',
            old_name='name',
            new_name='EnglishName',
        ),
        migrations.AddField(
            model_name='technique',
            name='otherName',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='technique',
            name='type',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
