# Generated by Django 4.1.2 on 2022-12-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutJournal', '0004_rename_name_technique_englishname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='technique',
            name='type',
            field=models.CharField(max_length=15),
        ),
    ]
