# Generated by Django 4.1.2 on 2022-12-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutJournal', '0004_alter_trainingsession_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='content',
            field=models.TextField(max_length=2500),
        ),
    ]
