# Generated by Django 4.1.2 on 2023-02-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutJournal', '0004_alter_trainingsession_minuteslength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='hoursLength',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='minutesLength',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
