# Generated by Django 4.1.2 on 2022-12-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutJournal', '0005_alter_technique_description_alter_technique_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='type',
            field=models.CharField(choices=[('Choke', ' Choke'), ('Throw', 'Throw'), ('Lever', 'Lever'), ('Sweep', 'Sweep'), ('Position', 'Position')], max_length=15),
        ),
    ]
