# Generated by Django 4.1.2 on 2023-02-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutJournal', '0007_trainingsession_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingsession',
            old_name='time',
            new_name='timestamp',
        ),
    ]
