# Generated by Django 4.1.2 on 2022-12-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutJournal', '0007_alter_technique_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='EnglishName',
            field=models.CharField(max_length=42, unique=True),
        ),
    ]
