# Generated by Django 4.1.2 on 2023-02-21 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WorkoutJournal', '0008_rename_time_trainingsession_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='addedByUser',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='user',
            field=models.ForeignKey(blank=True, default=45, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
