# Generated by Django 4.1.2 on 2023-03-18 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clubs', '0027_delete_clubtrainingsession'),
        ('WorkoutJournal', '0009_remove_trainingsession_addedbyuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='user',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clubs.club'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
