# Generated by Django 4.1.2 on 2023-03-29 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0027_delete_clubtrainingsession'),
        ('WorkoutJournal', '0012_remove_trainingsession_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clubs.club'),
        ),
    ]
