# Generated by Django 4.1.2 on 2022-12-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_register', '0002_alter_userprofile_avatar_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='belt',
            field=models.CharField(choices=[('NoInfo', 'No Info'), ('WhiteBelt', 'White Belt'), ('BlueBelt', 'Blue Belt'), ('PurpleBelt', 'Purple Belt'), ('BrownBelt', 'Brown Belt'), ('BlackBelt', 'Black Belt')], max_length=16),
        ),
    ]
