# Generated by Django 4.1.2 on 2023-01-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_register', '0006_alter_userprofile_belt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='belt',
            field=models.CharField(choices=[('No Info', 'No Info'), ('White Belt', 'White Belt'), ('Blue Belt', 'Blue Belt'), ('Purple Belt', 'Purple Belt'), ('Brown Belt', 'Brown Belt'), ('Black Belt', 'Black Belt')], default='No Info', max_length=16),
        ),
    ]
