# Generated by Django 4.1.2 on 2023-01-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0002_alter_club_authorizeduser_alter_club_estabilished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clubs_logo'),
        ),
    ]
