# Generated by Django 4.1.2 on 2023-01-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0006_club_creator_alter_club_authorizeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='website',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, default='defaultLogo.png', null=True, upload_to='clubs_logo'),
        ),
    ]
