# Generated by Django 4.1.2 on 2023-01-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0007_club_website_alter_club_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='club',
            name='city',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
