# Generated by Django 4.1.2 on 2023-01-24 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clubs', '0009_membership_remove_club_authorizeduser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('REJECTED', 'REJECTED')], default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userRequest', to=settings.AUTH_USER_MODEL),
        ),
    ]
