# Generated by Django 4.1.2 on 2023-01-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0010_request_status_alter_request_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='membershipType',
        ),
        migrations.AddField(
            model_name='usermembership',
            name='authorized',
            field=models.CharField(choices=[('FULL', 'FULL'), ('TRAININGS', 'TRAININGS'), ('NO', 'NO')], default='NO', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermembership',
            name='memberType',
            field=models.CharField(choices=[('Head', 'Head'), ('Instructor', 'Instructor'), ('Professor', 'Professor'), ('Student', 'Student')], default='Student', max_length=40),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
