# Generated by Django 4.1.2 on 2023-01-25 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0011_delete_membership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='membersClub', to='Clubs.club'),
            preserve_default=False,
        ),
    ]
