# Generated by Django 4.1.2 on 2023-02-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0014_alter_request_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='authorized',
            field=models.CharField(choices=[('FULL', 'FULL'), ('TRAININGS', 'TRAININGS'), ('NO', 'NO')], default='NO', max_length=30),
        ),
    ]
