# Generated by Django 4.1.2 on 2023-02-14 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clubs', '0015_alter_usermembership_authorized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
