# Generated by Django 4.1.2 on 2023-02-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0018_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='friday',
            field=models.JSONField(default={'type': 'time'}),
        ),
        migrations.AddField(
            model_name='schedule',
            name='monday',
            field=models.JSONField(default={'type': 'time'}),
        ),
        migrations.AddField(
            model_name='schedule',
            name='saturday',
            field=models.JSONField(default={'type': 'time'}),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sunday',
            field=models.JSONField(default={'type': 'time'}),
        ),
        migrations.AddField(
            model_name='schedule',
            name='thursday',
            field=models.JSONField(default={'type': 'time'}),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tuesday',
            field=models.JSONField(default={'type': 'time'}),
        ),
        migrations.AddField(
            model_name='schedule',
            name='wednesday',
            field=models.JSONField(default={'type': 'time'}),
        ),
    ]
