# Generated by Django 4.1.2 on 2023-02-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0019_schedule_friday_schedule_monday_schedule_saturday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='friday',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='saturday',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday',
            field=models.JSONField(default=dict),
        ),
    ]
