# Generated by Django 4.1.2 on 2023-02-26 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0020_alter_schedule_friday_alter_schedule_monday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='ownerClub',
        ),
        migrations.AddField(
            model_name='schedule',
            name='club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Clubs.club'),
            preserve_default=False,
        ),
    ]
