# Generated by Django 4.1.2 on 2023-02-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0021_remove_schedule_ownerclub_schedule_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='saturday',
            new_name='Saturday',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='sunday',
            new_name='Sunday',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='tuesday',
            new_name='Tuesday',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='wednesday',
            new_name='Wednesday',
        ),
    ]
