# Generated by Django 4.1.2 on 2023-02-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0023_rename_friday_schedule_friday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='Friday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Monday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Saturday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Sunday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Thursday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Tuesday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Wednesday',
        ),
        migrations.AddField(
            model_name='schedule',
            name='field',
            field=models.JSONField(default=dict),
        ),
    ]
