# Generated by Django 4.1.2 on 2023-02-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0024_remove_schedule_friday_remove_schedule_monday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='field',
            new_name='Friday',
        ),
        migrations.AddField(
            model_name='schedule',
            name='Monday',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='schedule',
            name='Saturday',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='schedule',
            name='Sunday',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='schedule',
            name='Thursday',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='schedule',
            name='Tuesday',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='schedule',
            name='Wednesday',
            field=models.JSONField(default=dict),
        ),
    ]
