# Generated by Django 4.1.2 on 2023-03-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0026_clubtrainingsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubTrainingSession',
        ),
    ]
