# Generated by Django 4.1.2 on 2023-05-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
